// 여행 데이터. 사진 URL과 출처는 images.js (IMG, CREDITS)에 있습니다.
const TRIP = {
  title: '윤아와 함께하는 뉴질랜드 여행',
  subtitle: '2027년 2월 · 뉴질랜드 남섬 캠핑카 가족여행',
  dates: '2027. 2. 3 (수) ~ 2. 10 (수) · 7박 8일',
  hero: { img: IMG.hero },

  flights: [
    { date: '2월 1일 (월)', who: '아빠 · 엄마', from: 'ICN', fromName: '인천', dep: '21:50 출발', to: 'SYD', toName: '시드니', arr: '다음날 10:05 도착', dur: '10시간 15분' },
    { date: '2월 3일 (수)', who: '5명 함께', from: 'SYD', fromName: '시드니', dep: '09:15 출발', to: 'ZQN', toName: '퀸스타운', arr: '14:15 도착', dur: '3시간' },
    { date: '2월 10일 (수)', who: '5명 함께', from: 'CHC', fromName: '크라이스트처치', dep: '12:00 출발', to: 'SIN', toName: '싱가포르', arr: '17:40 도착', dur: '10시간 40분' },
    { date: '2월 13일 (토)', who: '5명 함께', from: 'SIN', fromName: '싱가포르', dep: '14:35 출발', to: 'ICN', toName: '인천', arr: '22:00 도착', dur: '6시간 25분' },
  ],

  camper: {
    name: 'Indie Campers · EU Comfort Standard',
    note: '2월 3일 퀸스타운 공항에서 인수 → 2월 10일 크라이스트처치에서 반납',
    link: 'https://indiecampers.com/discover/en-us/rvs/eu-comfort-standard',
  },

  stays: {
    teanau: { name: 'Tasman Holiday Parks – Te Anau', addr: '128 Te Anau Terrace, Te Anau 9600', phone: '+64 3 249 7462', link: 'https://tasmanholidayparks.com/south-island/southland/te-anau/', note: '테아나우 호숫가 홀리데이파크 · 캠핑카 파워사이트 + 객실 · 2월 3일~5일 3박', lat: -45.4144, lng: 167.7096 },
    queenstown: { name: 'Hampshire Holiday Parks – Queenstown Lakeview', addr: '4 Cemetery Road, Queenstown 9300', phone: '+64 3 442 7252', link: 'https://hampshireholidayparks.co.nz/park/queenstown-lakeview-holiday-park/', note: '퀸스타운 시내 도보 5분, 스카이라인 곤돌라 바로 옆 · 2월 6일 1박', lat: -45.0311, lng: 168.6554 },
    glentanner: { name: 'Glentanner Park Centre', addr: 'State Highway 80, Aoraki Mount Cook 7946', phone: '+64 3 435 1855', link: 'https://www.glentanner.co.nz/', note: '푸카키 호수 북쪽, 마운트쿡 국립공원 18km 앞 · 스탠다드 유닛 1 + 파워사이트 1 · 2월 7일~8일 2박', lat: -43.9148, lng: 170.1224 },
    christchurch: { name: 'North South Holiday Park', addr: '530 Sawyers Arms Road, Harewood, Christchurch 8051', phone: '+64 3 359 5993', link: 'https://www.northsouth.co.nz/', note: '크라이스트처치 공항에서 차로 약 5분 · 2월 9일 1박', lat: -43.4704, lng: 172.5696 },
  },

  // 전체 지도의 경로 (routes.js의 ROUTES 키)
  legs: [
    { id: 'd1_zqn_teanau', label: '2/3 퀸스타운 공항 → 테아나우' },
    { id: 'd3_teanau_milford', label: '2/5 테아나우 ↔ 밀포드사운드 (당일 왕복)', dayTrip: true },
    { id: 'd4_teanau_qt', label: '2/6 테아나우 → 애로우타운 → 퀸스타운' },
    { id: 'd5_qt_glentanner', label: '2/7 퀸스타운 → 린디스 패스 → 푸카키 (글렌태너)' },
    { id: 'd6_glentanner_mtcook', label: '2/8 글렌태너 ↔ 마운트쿡 (당일 왕복)', dayTrip: true },
    { id: 'd7_glentanner_chc', label: '2/9 글렌태너 → 테카포 → 크라이스트처치' },
    { id: 'd8_northsouth_chc', label: '2/10 숙소 → 크라이스트처치 공항' },
  ],

  // 전체 지도의 핀
  pins: [
    { label: '✈', air: true, name: '퀸스타운 공항 도착', note: '2월 3일 (수) 14:15 도착 · 캠핑카 인수', lat: -45.0193, lng: 168.7434 },
    { label: '1', name: '테아나우 · 3박', note: '2월 3일~5일 · Tasman Holiday Parks', lat: -45.4144, lng: 167.7096 },
    { label: '2', name: '퀸스타운 · 1박', note: '2월 6일 · Queenstown Lakeview Holiday Park', lat: -45.0311, lng: 168.6554 },
    { label: '3', name: '푸카키 호수 (글렌태너) · 2박', note: '2월 7일~8일 · Glentanner Park Centre', lat: -43.9148, lng: 170.1224 },
    { label: '4', name: '크라이스트처치 · 1박', note: '2월 9일 · North South Holiday Park', lat: -43.4704, lng: 172.5696 },
    { label: '✈', air: true, name: '크라이스트처치 공항 출발', note: '2월 10일 (수) 12:00 출발', lat: -43.4852, lng: 172.5355 },
    { label: '●', trip: true, name: '밀포드사운드', note: '2월 5일 당일 왕복 · 13:05 크루즈', lat: -44.6682, lng: 167.9270 },
    { label: '●', trip: true, name: '아오라키 / 마운트쿡', note: '2월 8일 하이킹', lat: -43.7346, lng: 170.0977 },
  ],

  days: [
    {
      n: 1, month: 2, day: 3, dow: '수',
      title: '퀸스타운 도착 → 테아나우',
      short: '공항에서 캠핑카를 받고 장을 본 뒤 테아나우로 이동 (약 2시간 30분)',
      summary: '오후 2시 15분 퀸스타운 공항 도착. 캠핑카를 인수하고 Pak\'nSave에서 장을 본 뒤, 와카티푸 호수를 따라 테아나우로 이동합니다 (약 171km, 2시간~2시간 30분). 저녁에는 테아나우 호숫가에서 노을 산책.',
      cover: IMG.devils_staircase,
      stay: 'teanau', stayLabel: '테아나우 체크인 (1/3박)',
      drive: { title: '퀸스타운 공항 → 테아나우 · 약 171km, 2시간~2시간 30분', note: '와카티푸 호수 남쪽 끝 킹스턴을 지나 SH6 → SH94 국도로 갑니다. 굽은 길이 많아 내비게이션 시간보다 여유 있게 잡으세요.' },
      legs: ['d1_zqn_teanau'],
      spots: [
        { name: '퀸스타운 공항 도착 · 캠핑카 인수', en: 'Queenstown Airport (ZQN)', tag: '14:15 도착', desc: '시드니에서 오전 9시 15분 출발, 오후 2시 15분 도착. 공항 근처에서 캠핑카(Indie Campers)를 인수합니다. 차량 설명과 서류 작성에 1시간 정도 걸릴 수 있어요.', meta: '인수 약 1시간', img: IMG.zqn, maps: 'Queenstown Airport', lat: -45.0193, lng: 168.7434 },
        { name: '장보기', en: "Pak'nSave Queenstown (Frankton)", desc: '공항에서 5분 거리의 대형 마트. 테아나우 3박 동안 먹을 식재료와 생활용품, 모레 밀포드에 가져갈 간식을 미리 사 두면 좋아요. 바로 옆 아시안 마트에서 한식 재료도 살 수 있어요. 자세한 목록은 아래 \'장보기 리스트\' 버튼에서.', meta: '1시간', img: IMG.paknsave, maps: "Pak'nSave Queenstown", page: '#/shopping', pageLabel: '🛒 장보기 리스트', lat: -45.0109, lng: 168.7492 },
        { name: '데블스 스테어케이스 전망대', en: "Devil's Staircase Lookout", tag: '전망대', desc: '와카티푸 호수를 끼고 도는 절벽길 구간의 전망대. 길고 푸른 호수와 산이 한눈에 들어오는 사진 포인트예요. 잠깐 정차해서 쉬어 가기 좋아요.', meta: '정차 10~15분', img: IMG.devils_staircase, maps: "Devil's Staircase Lookout", lat: -45.2457, lng: 168.7429 },
        { name: '킹스턴 호숫가 휴식', en: 'Kingston', desc: '와카티푸 호수 남쪽 끝의 작은 마을. 잔잔한 호숫가에서 다리를 쉬어가기 좋고, 여기부터는 호수를 벗어나 내륙 평원을 달립니다.', meta: '휴식 20분', img: IMG.kingston, maps: 'Kingston, Otago, New Zealand', lat: -45.3344, lng: 168.7175 },
        { name: '테아나우 호수 노을 산책', en: 'Te Anau Lakefront Walk', desc: '숙소에서 바로 걸어갈 수 있는 호숫가 산책로. 남섬에서 가장 큰 호수인 테아나우 호수 너머로 해가 집니다. 2월에는 오후 9시쯤 해가 져요.', meta: '저녁 식사 후 30분~1시간', img: IMG.teanau_lakefront, maps: 'Te Anau Lakefront', lat: -45.4181, lng: 167.7129 },
      ],
      tips: ['뉴질랜드는 좌측통행이에요. 첫날은 특히 천천히, 무리하지 않기.', '숙소 체크인은 오후 2시부터. 늦어질 경우 미리 전화해 주세요 (+64 3 249 7462).', '항공 지연으로 늦으면 장보기는 다음 날 테아나우에서 간단히 해도 괜찮아요.'],
    },
    {
      n: 2, month: 2, day: 4, dow: '목',
      title: '테아나우 · 반딧불 동굴',
      short: '반딧불 동굴 투어, 조류 보호구역, 케플러 트랙 맛보기 산책',
      summary: '이동 없이 테아나우에서 여유롭게 보내는 날. 배를 타고 건너가는 반딧불(글로웜) 동굴 투어가 메인이고, 호숫가 조류 보호구역과 케플러 트랙의 흔들다리를 가볍게 걸어요.',
      cover: IMG.glowworm,
      stay: 'teanau', stayLabel: '테아나우 연박 (2/3박)',
      drive: { title: '이동 없음 · 테아나우 주변', note: '반딧불 동굴 선착장은 숙소에서 걸어서 10분, 레인보우 리치는 차로 15분 거리예요.' },
      legs: [],
      spots: [
        { name: '테아나우 반딧불 동굴 투어', en: 'Te Anau Glowworm Caves', tag: '예약 필요', desc: '호수 건너편 석회동굴로 배를 타고 건너간 뒤, 작은 보트에 앉아 어둠 속에서 푸른 빛을 내는 반딧불이(글로웜)를 봅니다. 동굴 안에서는 조용히, 사진 촬영은 금지예요. 전체 2시간 15분 정도.', meta: '약 2시간 15분 · 레이크프론트 드라이브 RealNZ 센터에서 출발', img: IMG.glowworm, maps: 'RealNZ Te Anau Visitor Centre', link: 'https://www.realnz.com/en/experiences/glowworm-caves/te-anau-glowworm-caves/', linkLabel: 'RealNZ 예약', lat: -45.4208, lng: 167.7160 },
        { name: '테아나우 조류 보호구역', en: 'Punanga Manu o Te Anau · Bird Sanctuary', desc: '호숫가 산책로 옆에 있는 무료 조류 보호구역. 뉴질랜드에서만 볼 수 있는 희귀새 타카헤(takahē)를 가까이서 볼 수 있어요. 평지라 걷기 편합니다.', meta: '무료 · 30~40분', img: IMG.bird_sanctuary, maps: 'Te Anau Bird Sanctuary', lat: -45.4327, lng: 167.7133 },
        { name: '케플러 트랙 맛보기 · 레인보우 리치 흔들다리', en: 'Rainbow Reach Swing Bridge (Kepler Track)', desc: '뉴질랜드 대표 트레킹 코스인 케플러 트랙의 한 구간. 주차장에서 와이아우 강 위의 흔들다리까지 몇 분이면 갈 수 있고, 강변 숲길을 원하는 만큼 걷다가 돌아오면 됩니다.', meta: '테아나우에서 차로 15분 · 왕복 30분~1시간', img: IMG.rainbow_reach, maps: 'Rainbow Reach Swing Bridge, Te Anau', lat: -45.4780, lng: 167.7450 },
      ],
      tips: ['동굴 안은 어둡고 서늘해요. 얇은 겉옷을 챙기세요.', '내일 밀포드에 가져갈 런치·간식·물과 연료를 오늘 미리 준비해 두세요.'],
    },
    {
      n: 3, month: 2, day: 5, dow: '금',
      title: '밀포드사운드 크루즈',
      short: '밀포드 로드 드라이브 + 13:05 크루즈 (예약 완료)',
      summary: '오전 9시 30분~10시에 테아나우를 출발해, 밀포드 로드의 경치 좋은 곳들을 들르며 밀포드사운드로 갑니다. 오후 1시 5분 크루즈(2시간, 런치박스 포함) 예약 완료. 돌아오는 길에는 레이크 건 숲길 산책.',
      cover: IMG.milford_hero,
      stay: 'teanau', stayLabel: '테아나우 연박 (3/3박)',
      drive: { title: '테아나우 ↔ 밀포드사운드 · 편도 약 120km, 2시간 이상 (당일 왕복)', note: '중간에 주유소·상점·휴대전화 신호가 거의 없어요. 테아나우에서 주유를 가득 채우고 음식과 물을 준비하세요. 크루즈 3시간 전 출발 권장.' },
      legs: ['d3_teanau_milford'],
      spots: [
        { name: '에글린턴 계곡', en: 'Eglinton Valley', desc: '빙하가 깎아 만든 넓고 평평한 계곡. 황금빛 초원 양옆으로 산이 병풍처럼 늘어서 있어요. 길가 전망 포인트에서 잠깐 정차.', meta: '정차 10분', img: IMG.eglinton, maps: 'Eglinton Valley Lookout', lat: -45.0621, lng: 167.9937 },
        { name: '미러 레이크 (거울 호수)', en: 'Mirror Lakes', desc: '바람 없는 아침이면 얼(Earl) 산맥이 호수에 거울처럼 비칩니다. 주차장에서 나무 데크길로 5분, 평지라 누구나 편하게 볼 수 있어요.', meta: '15분', img: IMG.mirror_lakes, maps: 'Mirror Lakes, Fiordland', lat: -45.0284, lng: 168.0110 },
        { name: '놉스 플랫', en: 'Knobs Flat', desc: '밀포드 로드 중간의 휴게 지점. 화장실과 작은 안내소가 있어요. 밀포드까지 화장실이 거의 없으니 여기서 들르세요.', meta: '화장실 · 10분', img: IMG.knobs_flat, maps: 'Knobs Flat', lat: -44.9669, lng: 168.0108 },
        { name: '몽키 크리크', en: 'Monkey Creek', desc: '빙하수가 흐르는 맑은 개울. 물이 깨끗해 그대로 마셔도 된다고 알려져 있고, 운이 좋으면 산앵무새 케아(kea)를 만날 수 있어요. 케아에게 먹이는 주지 마세요.', meta: '10분', img: IMG.monkey_creek, maps: 'Monkey Creek, Fiordland', lat: -44.8009, lng: 168.0213 },
        { name: '호머 터널 입구 대기', en: 'Homer Tunnel', desc: '산을 뚫은 1.2km 길이의 일방통행 터널. 신호에 따라 최대 15분 정도 기다리는 동안 주변 절벽과 폭포를 구경할 수 있어요. 터널을 지나면 밀포드까지 내리막길입니다.', meta: '대기 최대 15분', img: IMG.homer_tunnel, maps: 'Homer Tunnel', lat: -44.7642, lng: 167.9812 },
        { name: '밀포드사운드 크루즈', en: 'Milford Sound Cruise', tag: '13:05 · 예약 완료', desc: '13:05 출발, 2시간. 피오르 안쪽 바다로 나가며 마이터 피크와 수백 미터 높이의 폭포(스털링 폭포 등)를 배 위에서 봅니다. 물개와 돌고래를 볼 때도 있어요. 런치박스 포함. 터미널 주차장에서 터미널까지 걸어서 10분이니 12시 20분 전에는 주차하세요.', meta: '2시간 · 런치박스 포함', img: IMG.milford_cruise, maps: 'Milford Sound Visitor Terminal', lat: -44.6682, lng: 167.9270 },
        { name: '레이크 건 자연 탐방로', en: 'Lake Gunn Nature Walk', tag: '돌아오는 길 추천', desc: '돌아오는 길에 들르기 좋은 45분짜리 원형 숲길. 이끼 낀 너도밤나무 숲 사이로 평탄하게 이어져 걷기 편하고, 호숫가에서 산이 비치는 풍경도 볼 수 있어요.', meta: '45분 · 평지', img: IMG.lake_gunn, maps: 'Lake Gunn Nature Walk', lat: -44.8860, lng: 168.0930 },
      ],
      tips: ['출발 전 SH94 밀포드 로드 도로 상태를 꼭 확인하세요 (NZTA Milford Road Status).', '밀포드는 연중 비가 많이 와요. 비옷과 벌레 기피제(샌드플라이 대비)를 준비하세요.', '크루즈 터미널 주차장에서 터미널까지 걸어서 10분 정도 걸립니다.'],
    },
    {
      n: 4, month: 2, day: 6, dow: '토',
      title: '애로우타운 · 퀸스타운',
      short: '테아나우 체크아웃 → 애로우타운 관광, 온천, 퀸스타운 곤돌라',
      summary: '테아나우를 떠나 퀸스타운으로 돌아옵니다 (약 2시간 30분). 금광 마을 애로우타운을 둘러보고 온센 핫풀에서 온천(예약 필요), 저녁에는 스카이라인 곤돌라에서 퀸스타운 야경을 봅니다.',
      cover: IMG.skyline,
      stay: 'queenstown', stayLabel: '퀸스타운 체크인 (1박)',
      drive: { title: '테아나우 → 애로우타운 → 퀸스타운 · 약 200km, 3시간', note: '오전에 출발해 왔던 길(SH94 → SH6)로 돌아가 프랭크턴을 지나 애로우타운으로. 숙소 체크인은 오후 3시부터.' },
      legs: ['d4_teanau_qt'],
      spots: [
        { name: '애로우타운 역사지구', en: 'Historic Arrowtown', desc: '1860년대 골드러시 때 생긴 마을. 버킹엄 스트리트를 따라 옛 건물들이 카페와 상점으로 남아 있어요. 천천히 걸으며 점심 먹기 좋아요.', meta: '1~2시간', img: IMG.arrowtown, maps: 'Buckingham Street, Arrowtown', lat: -44.9406, lng: 168.8351 },
        { name: '중국인 광산 정착지', en: 'Arrowtown Chinese Settlement', desc: '금을 캐러 온 중국인 광부들이 살던 돌집 유적. 마을 끝 개울가에 있고 걸어서 몇 분 거리예요. 무료.', meta: '무료 · 20~30분', img: IMG.chinese_settlement, maps: 'Arrowtown Chinese Settlement', lat: -44.9382, lng: 168.8257 },
        { name: '온센 핫풀', en: 'Onsen Hot Pools', tag: '예약 필요', desc: '쇼토버 강 협곡을 내려다보는 개인 온천탕. 큰 창을 열면 절벽과 강이 그대로 보여요. 인기가 많아 미리 예약해야 합니다.', meta: '1시간 · 애로우타운에서 차로 15분', img: IMG.onsen, maps: 'Onsen Hot Pools, Arthurs Point', link: 'https://www.onsen.co.nz/experiences/', linkLabel: '온센 예약', lat: -44.9810, lng: 168.6854 },
        { name: '카와라우 다리 번지점프 전망대', en: 'AJ Hackett Kawarau Bridge Bungy', desc: '세계 최초의 상업 번지점프 장소(1988년). 뛰지 않아도 다리와 전망대에서 뛰어내리는 사람들을 구경할 수 있고, 카페도 있어요.', meta: '구경 30분', img: IMG.kawarau_bridge, maps: 'Kawarau Bridge Bungy Centre', lat: -45.0087, lng: 168.8996 },
        { name: '깁스턴 밸리 와이너리', en: 'Gibbston Valley Winery', desc: '센트럴 오타고 피노누아로 유명한 와이너리. 와인 시음, 치즈 가게, 레스토랑이 있어요. 운전하는 사람은 시음 주의!', meta: '30분~1시간', img: IMG.gibbston, maps: 'Gibbston Valley Winery', lat: -45.0123, lng: 168.9152 },
        { name: '스카이라인 곤돌라 · 밥스 피크 전망대', en: 'Skyline Gondola & Luge', desc: '퀸스타운 시내에서 곤돌라를 타고 밥스 피크에 오르면 와카티푸 호수와 리마커블스 산맥이 한눈에 들어와요. 루지(썰매 카트)도 있고, 해 질 무렵 올라가면 야경까지 볼 수 있어요. 숙소에서 걸어서 5분.', meta: '저녁 · 1~2시간', img: IMG.skyline, maps: 'Skyline Queenstown', link: 'https://www.skyline.co.nz/en/queenstown/', linkLabel: '스카이라인 예약', lat: -45.0283, lng: 168.6561 },
      ],
      tips: ['온센 핫풀 예약 시간에 맞춰 하루 동선을 정하세요.', '퀸스타운 숙소는 시내까지 걸어서 5분이라 저녁은 시내에서 드시면 좋아요.'],
    },
    {
      n: 5, month: 2, day: 7, dow: '일',
      title: '린디스 패스 넘어 푸카키 호수로',
      short: '크롬웰 과일 가게, 린디스 패스, 연어 맛보기 → 글렌태너 체크인',
      summary: '퀸스타운을 떠나 카와라우 협곡, 과일 산지 크롬웰, 황금빛 린디스 패스를 넘어 마운트쿡 아래 푸카키 호수로 갑니다. 약 3시간 30분~4시간의 긴 드라이브. 저녁은 푸카키 연어.',
      cover: IMG.lindis_pass,
      stay: 'glentanner', stayLabel: '푸카키 (글렌태너) 체크인 (1/2박)',
      drive: { title: '퀸스타운 → 크롬웰 → 린디스 패스 → 글렌태너 · 약 240km, 3시간 30분~4시간', note: 'SH6 카와라우 협곡 → 크롬웰 → SH8 린디스 패스 → 오마라마 → 트와이즐 → SH80. 글렌태너에는 주유소·상점이 없으니 트와이즐에서 주유와 장보기를 하세요.' },
      legs: ['d5_qt_glentanner'],
      spots: [
        { name: '로링 메그 전망대', en: 'Roaring Meg Lookout', desc: '카와라우 협곡을 지나다 만나는 전망대. 하얗게 거품을 일으키며 흐르는 급류와 작은 수력발전소를 볼 수 있어요.', meta: '정차 10분', img: IMG.roaring_meg, maps: 'Roaring Meg Lookout', lat: -45.0014, lng: 169.0715 },
        { name: '크롬웰 과일 농장 가게', en: 'Cromwell Fruit Stalls · Jones Family Fruit Stall', desc: '뉴질랜드 최고의 과일 산지. 2월은 체리·살구·복숭아·천도복숭아 철이라 농장 직판장에서 갓 딴 과일을 사기 좋아요. 마을 입구의 대형 과일 조형물도 사진 포인트.', meta: '30분', img: IMG.cromwell, maps: 'Jones Family Fruit Stall, Cromwell', lat: -45.0429, lng: 169.1868 },
        { name: '린디스 패스 정상 전망대', en: 'Lindis Pass Summit Lookout', desc: '해발 971m, 남섬에서 손꼽히는 경치 좋은 고갯길. 나무 없이 황금빛 터석 풀로 덮인 산들이 굽이굽이 이어집니다. 정상 주차장에서 잠깐 내려 사진을 찍으세요.', meta: '정차 10~15분', img: IMG.lindis_pass, maps: 'Lindis Pass Summit Lookout', lat: -44.5883, lng: 169.6431 },
        { name: '연어 맛보기', en: 'High Country Salmon / Mt Cook Alpine Salmon', desc: '빙하수 수로에서 키운 연어를 파는 농장 직판장. 갓 뜬 연어회와 훈제연어를 저렴하게 살 수 있어요. 트와이즐 가는 길의 하이컨트리 새먼, 또는 푸카키 호수 쪽 마운트쿡 알파인 새먼. 저녁 식사로 추천.', meta: '30분', img: IMG.salmon, maps: 'High Country Salmon, Twizel', lat: -44.2911, lng: 170.0845 },
        { name: '푸카키 호수 · 글렌태너 체크인', en: 'Lake Pukaki · Glentanner Park Centre', tag: '체크인', desc: '우윳빛 하늘색 호수 끝에 마운트쿡이 서 있는 풍경. 글렌태너는 호수 북쪽 끝, 마운트쿡 국립공원 입구 18km 앞에 있는 홀리데이파크예요. 스탠다드 유닛 1실 + 파워사이트 1.', meta: '체크인', img: IMG.pukaki, maps: 'Glentanner Park Centre', lat: -43.9148, lng: 170.1224 },
      ],
      tips: ['일요일 장거리 이동이에요. 해 지기 전에 도착하도록 오후 일찍 출발하세요.', '글렌태너에는 덤프 스테이션, 주유소, 식료품점이 없어요. 트와이즐에서 미리 처리하세요.', '리셉션 마감 후 도착하면 외부에 게시된 늦은 도착 안내를 따르세요.'],
    },
    {
      n: 6, month: 2, day: 8, dow: '월',
      title: '마운트쿡 하이킹',
      short: '후커 밸리 트랙, 키아 포인트, 타스만 빙하 전망대',
      summary: '뉴질랜드 최고봉 아오라키/마운트쿡(3,724m) 아래에서 걷는 날. 대표 코스인 후커 밸리 트랙(왕복 10km, 3시간)을 중심으로, 체력에 따라 키아 포인트와 타스만 빙하 전망대를 더합니다.',
      cover: IMG.hooker_valley,
      stay: 'glentanner', stayLabel: '푸카키 (글렌태너) 연박 (2/2박)',
      drive: { title: '글렌태너 ↔ 마운트쿡 빌리지 · 편도 약 20km, 20분', note: 'SH80을 따라 호수를 끼고 국립공원으로 들어갑니다. 후커 밸리 트랙은 화이트 호스 힐 주차장에서 시작해요.' },
      legs: ['d6_glentanner_mtcook'],
      spots: [
        { name: '후커 밸리 트랙', en: 'Hooker Valley Track', tag: '대표 추천', desc: '뉴질랜드에서 가장 유명한 당일 트레킹 코스. 흔들다리 3개를 건너 빙하 호수(후커 호수)까지 가면 눈 덮인 마운트쿡이 정면에 보여요. 계단이 거의 없는 완만한 자갈길이라 천천히 걸으면 누구나 갈 수 있어요.', meta: '왕복 약 10km · 3시간 · 화이트 호스 힐 주차장 출발', img: IMG.hooker_valley, maps: 'White Horse Hill Campground', lat: -43.7184, lng: 170.0984 },
        { name: '키아 포인트 트랙', en: 'Kea Point Track', desc: '같은 주차장에서 출발하는 짧은 코스. 뮬러 빙하 호수와 마운트쿡, 세프턴산을 내려다보는 전망대까지 완만하게 이어집니다.', meta: '왕복 1시간', img: IMG.kea_point, maps: 'Kea Point Track', lat: -43.7256, lng: 170.0914 },
        { name: '타스만 빙하 전망대', en: 'Tasman Glacier Viewpoint', desc: '뉴질랜드에서 가장 긴 빙하와 빙하호를 내려다보는 전망대. 주차장에서 계단을 15분 정도 오릅니다. 호수 위에 떠 있는 얼음덩이(빙산)를 볼 수 있어요.', meta: '왕복 40분 · 계단 있음', img: IMG.tasman_glacier, maps: 'Tasman Glacier View Track car park', lat: -43.6750, lng: 170.1720 },
        { name: '허미티지 호텔 · 힐러리 알파인 센터', en: 'Hermitage Hotel & Sir Edmund Hillary Alpine Centre', desc: '마운트쿡 빌리지의 역사 깊은 호텔. 창밖으로 마운트쿡이 보이는 카페에서 커피나 식사를 할 수 있고, 에베레스트 최초 등정자 힐러리 경의 전시관도 있어요. 하이킹 후 쉬어 가기 좋아요.', meta: '1시간', img: IMG.hermitage, maps: 'The Hermitage Hotel, Mount Cook', lat: -43.7346, lng: 170.0977 },
      ],
      tips: ['산 날씨는 빨리 바뀌어요. 바람막이, 모자, 선크림, 물, 간식을 꼭 챙기세요.', '후커 밸리 트랙은 오전 일찍 출발하면 한산하고 바람도 적어요.', '국립공원 안에는 상점이 거의 없어요. 점심은 도시락이나 허미티지 카페에서.'],
    },
    {
      n: 7, month: 2, day: 9, dow: '화',
      title: '테카포 호수 → 크라이스트처치',
      short: '선한 목자의 교회, 마운트 존 전망대, 페얼리 파이 → 크라이스트처치',
      summary: '글렌태너를 떠나 테카포 호수를 구경하고 크라이스트처치로 이동하는 긴 하루. 선한 목자의 교회와 마운트 존 전망대를 들르고, 페얼리 베이크하우스에서 파이로 점심. 공항 근처 캠핑장에 체크인합니다.',
      cover: IMG.good_shepherd,
      stay: 'christchurch', stayLabel: '크라이스트처치 체크인 (1박)',
      drive: { title: '글렌태너 → 테카포 → 페얼리 → 크라이스트처치 · 약 310km, 4시간 이상', note: 'SH80 → SH8 → 테카포 → 페얼리 → SH79 → SH1. 휴식 포함 5시간 정도 잡으세요. 마지막 날이니 캠핑카 반납 전 청수·폐수·연료 규정을 확인해 두세요.' },
      legs: ['d7_glentanner_chc'],
      spots: [
        { name: '선한 목자의 교회 & 양치기 개 동상', en: 'Church of the Good Shepherd', desc: '1935년에 지어진 작은 돌 교회. 창문 너머로 테카포 호수와 산이 액자처럼 보여요. 옆에는 매켄지 지방을 개척한 양치기 개들을 기리는 동상이 있습니다. 뉴질랜드에서 가장 많이 사진 찍히는 곳 중 하나.', meta: '30분', img: IMG.good_shepherd, maps: 'Church of the Good Shepherd, Lake Tekapo', lat: -44.0033, lng: 170.4825 },
        { name: '마운트 존 전망대 & 아스트로 카페', en: 'Mt John Observatory & Astro Cafe', desc: '테카포 마을 뒤 산꼭대기의 천문대. 차로 올라갈 수 있고(유료 도로), 정상 카페에서 커피를 마시며 테카포 호수 전체를 360도로 내려다봅니다.', meta: '1시간 · 유료 도로', img: IMG.mt_john, maps: 'Mount John Observatory', link: 'https://www.darkskyproject.co.nz/', linkLabel: '다크 스카이 프로젝트', lat: -43.9854, lng: 170.4644 },
        { name: '페얼리 베이크하우스', en: 'Fairlie Bakehouse', desc: '뉴질랜드에서 파이로 가장 유명한 빵집. 연어 베이컨 파이와 포크벨리 파이가 인기예요. 점심으로 딱.', meta: '점심 · 30분', img: IMG.fairlie, maps: 'Fairlie Bakehouse', lat: -44.0986, lng: 170.8295 },
        { name: '크라이스트처치 캠핑장 체크인', en: 'North South Holiday Park', tag: '체크인', desc: '공항에서 5분 거리의 홀리데이파크. 내일 정오 출국에 맞춰 캠핑카 정리와 짐 싸기. 시간이 남으면 시내 대성당 광장이나 식물원을 둘러봐도 좋아요.', meta: '체크인', img: IMG.christchurch, maps: 'North South Holiday Park, Christchurch', lat: -43.4704, lng: 172.5696 },
      ],
      tips: ['페얼리 베이크하우스는 점심시간에 줄이 길어요.', '캠핑카 반납 조건(청수 채우기, 폐수 비우기, 연료)을 렌터카 회사에 확인해 두세요.'],
    },
    {
      n: 8, month: 2, day: 10, dow: '수',
      title: '캠핑카 반납 · 출국',
      short: '캠핑카 반납 후 12:00 크라이스트처치 → 싱가포르',
      summary: '체크아웃 후 캠핑카를 반납하고 크라이스트처치 공항으로. 낮 12시 싱가포르행 비행기로 뉴질랜드 여행을 마무리합니다. 싱가포르에서 3일 머문 뒤 2월 13일 서울 도착.',
      cover: IMG.chc,
      stay: 'christchurch', stayLabel: '크라이스트처치 체크아웃',
      drive: { title: '숙소 → 캠핑카 반납 → 크라이스트처치 공항 · 약 5분', note: '국제선은 출발 3시간 전 공항 도착 권장. 반납 시간까지 역산해서 아침 일찍 움직이세요.' },
      legs: ['d8_northsouth_chc'],
      spots: [
        { name: '캠핑카 반납', en: 'Campervan Return', desc: '청수·폐수 처리와 연료를 확인한 뒤 반납합니다. 차 안에 두고 내리는 물건이 없는지 마지막으로 점검하세요.', meta: '오전', img: IMG.campervan, maps: 'Christchurch Airport' },
        { name: '크라이스트처치 공항 출발', en: 'Christchurch Airport (CHC)', tag: '12:00 출발', desc: '12:00 출발 → 싱가포르 17:40 도착 (10시간 40분). 5명 함께.', meta: '출발 3시간 전 도착', img: IMG.chc, maps: 'Christchurch International Airport', lat: -43.4852, lng: 172.5355 },
      ],
      tips: ['출국 전날 저녁에 짐을 미리 정리해 두세요.', '싱가포르 환승: 2월 13일(토) 14:35 싱가포르 출발 → 22:00 인천 도착.'],
    },
  ],

  // 1일차 장보기 가이드 (#/shopping)
  shopping: {
    verified: '2026-09-03',
    intro: '5명 · 7박 · 첫 3박은 테아나우 연박. 퀸스타운 프랭크턴에서 한 번에 크게 사고, 테아나우와 트와이즐에서 신선식품만 보충하면 됩니다. 아침은 매일 캠핑카, 점심은 외식·도시락 반반, 저녁은 캠핑카 4~5회 기준으로 수량을 잡았어요.',
    stores: [
      { tag: '메인', name: "Pak'nSave Queenstown", addr: '302 Hawthorne Drive, Frankton, Queenstown 9300', hours: '매일 07:00–22:00', phone: '03 409 1000', desc: '공항에서 차로 5분. 뉴질랜드에서 가장 저렴한 대형마트예요. 식료품·생활용품·맥주·와인을 한 번에.', maps: "Pak'nSave Queenstown", link: 'https://www.paknsave.co.nz/south-island/otago-and-southland/queenstown' },
      { tag: '한식 재료', name: 'New Star Asian Market', addr: 'The Landing, 4/5 Hawthorne Drive, Frankton', hours: '영업시간은 매장에 확인', phone: '03 441 3016', desc: "Pak'nSave 바로 옆 아시안 마트. 고추장·된장·김치·라면·두부·쌀.", maps: 'New Star Asian Market, The Landing, Frankton', link: 'https://www.thelandingqueenstown.co.nz/new-star/' },
      { tag: '한식 재료', name: "Kim's Mart", addr: 'B03, 19 Grant Road, Frankton (Queenstown Central)', hours: '매일 09:00–20:00', desc: '한국 과자·소스·라면 등. 퀸스타운 센트럴 쇼핑센터 안, 공항에서 차로 5분.', maps: "Kim's Mart, Queenstown Central, Frankton", link: 'https://www.kims.co.nz/' },
      { tag: '재보급', name: 'FreshChoice Te Anau', addr: '5 Milford Crescent, Te Anau', desc: '테아나우에서 가장 큰 마트. 빵·우유·과일·채소 보충과 밀포드 가는 날 준비.', maps: 'FreshChoice Te Anau', link: 'https://teanau.store.freshchoice.co.nz/' },
      { tag: '재보급', name: 'Four Square Twizel', addr: 'Market Place, Twizel', desc: '글렌태너로 가기 전 마지막 마트. 글렌태너 파크에는 카페와 기념품점만 있고, 마운트쿡 빌리지는 허미티지 소매점에서 소량의 식료품을 비싸게 파는 정도예요.', maps: 'Four Square Twizel' },
    ],
    notes: [
      '일회용 비닐봉지는 2019년부터 금지라 장바구니를 챙기세요. 마트에서 재사용 가방을 살 수 있어요.',
      '플라스틱 일회용 접시·그릇·수저와 농산물용 비닐봉지도 2023년부터 판매 금지예요. 일회용이 필요하면 종이·목재 제품만 있어요.',
      '마트에서는 맥주와 와인만 팔아요(양주는 전문점). 계산할 때 신분증을 요구할 수 있어요.',
      '수돗물은 그냥 마셔도 됩니다. 생수는 차에 둘 최소량만 사고 캠핑장에서 물통에 받아 쓰세요.',
      '캠핑카에 포함된 것: 냄비 2·프라이팬·그릴팬, 접시·볼·컵·수저 각 4개, 도마·칼·주걱·샐러드볼·커피포트, 스펀지·주방세제. 5명이라 식기 1인분을 더 사세요.',
      '캠핑카에 없는 것: 수건·화장지·비누. 침구와 야외 테이블·의자는 유료 옵션이니 예약 내역을 확인하세요.',
      '입국할 때 음식은 전부 신고해야 해요(한국에서 가져오는 라면·김 포함). 신고하면 대부분 통과됩니다.',
      '캠핑장 샤워·세탁기는 $1·$2 동전을 쓰는 곳이 많아요. 마트 계산대에서 잔돈을 만들어 두세요.',
    ],
    groups: [
      { emoji: '🥣', title: '아침·간단식', where: '퀸스타운 첫 장보기 · 테아나우 3박분', items: [
        { name: '식빵', qty: '2봉' }, { name: '계란', qty: '20개' }, { name: '우유', qty: '2L × 2' }, { name: '버터', qty: '1개' }, { name: '잼', qty: '1개' }, { name: '시리얼', qty: '1박스' }, { name: '요거트', qty: '1kg' }, { name: '슬라이스 치즈', qty: '1팩' }, { name: '햄', qty: '2팩' }, { name: '바나나', qty: '1송이' },
        { name: '제철 과일', qty: '2~3일치', note: '2월은 체리·살구·복숭아·천도복숭아 철. 크롬웰 직판장에서 더 사요' },
      ] },
      { emoji: '🥪', title: '점심·도시락', where: '퀸스타운 첫 장보기', items: [
        { name: '크래커', qty: '2팩' }, { name: '견과류', qty: '1봉' }, { name: '초콜릿·에너지바', qty: '10개' },
        { name: '컵라면', qty: '5개', note: '밀포드·마운트쿡 가는 날 보온병 물로' },
        { name: '보온병', qty: '1~2개', note: '집에서 안 가져왔으면' },
      ] },
      { emoji: '🍚', title: '저녁·한식', where: '캠핑카 저녁 4~5회분 · 한식 재료는 아시안 마트', items: [
        { name: '쌀', qty: '2~3kg', note: '5명 한 끼 약 450g × 5회. medium grain 또는 아시안 마트' },
        { name: '라면', qty: '10개', note: '비상식·야식' },
        { name: '김치', qty: '1통', note: '아시안 마트' }, { name: '고추장·된장', qty: '소용량 1개씩', note: '아시안 마트' },
        { name: '김', qty: '1팩' }, { name: '참치캔', qty: '4개' }, { name: '스팸', qty: '2개' },
        { name: '소고기·양고기', qty: '2끼분', note: '뉴질랜드 특산, 한국보다 저렴해요' }, { name: '소시지', qty: '1팩' },
        { name: '채소 (양파·마늘·감자·당근·애호박·버섯)', qty: '3일치' }, { name: '샐러드믹스', qty: '1봉' },
        { name: '두부', qty: '2모', note: '아시안 마트' },
      ] },
      { emoji: '🧂', title: '조미료·기본', where: '퀸스타운 첫 장보기 · 소용량으로', items: [
        { name: '소금·후추', qty: '소용량 1개씩' }, { name: '식용유', qty: '소병 1' }, { name: '간장', qty: '소병 1' }, { name: '설탕', qty: '소량 1' },
        { name: '참기름·고춧가루', qty: '소용량', note: '아시안 마트' }, { name: '인스턴트 커피·티백', qty: '1개씩' }, { name: '케첩·마요네즈', qty: '소용량 1개씩' },
      ] },
      { emoji: '🥤', title: '음료', where: '퀸스타운 첫 장보기', items: [
        { name: '생수', qty: '2L × 4', note: '차에 둘 최소량. 수돗물을 마실 수 있어요' },
        { name: '물통', qty: '5~10L 1개', note: '캠핑장 수돗물로 채워 써요' },
        { name: '주스', qty: '2L × 2' }, { name: '맥주·와인', qty: '취향껏', note: '마트에서 구매, 신분증 지참' }, { name: '보온병용 차', qty: '1개' },
      ] },
      { emoji: '🍳', title: '주방 소모품', where: '퀸스타운 첫 장보기', items: [
        { name: '키친타월', qty: '2롤' }, { name: '쓰레기봉투', qty: '1롤' }, { name: '지퍼백', qty: '1박스' }, { name: '알루미늄 포일·랩', qty: '1개씩' }, { name: '수세미·행주', qty: '2개씩' },
        { name: '다회용 컵·접시·수저', qty: '1인분', note: '키트가 4인분이라 5명이면 부족. 일회용은 종이·목재 제품만 있어요' },
        { name: '라이터', qty: '1개' }, { name: '아이스팩·쿨러백', qty: '2개 · 1개' },
      ] },
      { emoji: '🧻', title: '위생·욕실', where: '퀸스타운 첫 장보기 · 캠핑카에 없는 것들', items: [
        { name: '화장지', qty: '6롤', note: '캠핑카 변기용은 빨리 녹는 제품' }, { name: '수건', qty: '5장', note: '캠핑카 미포함' },
        { name: '비누·샴푸·바디워시', qty: '소용량 1개씩', note: '캠핑카 미포함' }, { name: '치약·칫솔', qty: '5인분' },
        { name: '손소독제', qty: '1개' }, { name: '물티슈', qty: '2팩' }, { name: '세탁세제·빨래집게', qty: '소량 1 · 1팩' },
      ] },
      { emoji: '🩹', title: '건강·안전', where: '퀸스타운 첫 장보기 · 마트 또는 약국', items: [
        { name: '자외선차단제 SPF50+', qty: '2개', note: '뉴질랜드 자외선은 한국보다 훨씬 강해요' },
        { name: '샌드플라이 기피제', qty: '2개', note: '밀포드 필수. 현지 브랜드(Bushman, Aeroguard Tropical Strength)' },
        { name: '물린 데 바르는 연고', qty: '1개' }, { name: '진통해열제 (Panadol)', qty: '1개' }, { name: '밴드', qty: '1박스' }, { name: '멀미약', qty: '1개' }, { name: '립밤', qty: '5개' },
      ] },
      { emoji: '🔦', title: '캠핑카 생활', where: '마트 또는 The Warehouse / Kmart (프랭크턴)', items: [
        { name: '손전등·헤드랜턴', qty: '2개' }, { name: '차량용 USB 충전기·보조배터리', qty: '1개 · 필요한 만큼' },
        { name: 'I형 멀티탭', qty: '1개', note: '뉴질랜드 플러그는 I형, 230V' }, { name: '슬리퍼', qty: '5켤레' }, { name: '장바구니', qty: '3개' },
        { name: '동전 ($1·$2)', qty: '$20 정도', note: '캠핑장 샤워·세탁기용' },
      ] },
      { emoji: '🔁', title: '보충 (테아나우·트와이즐)', where: '테아나우 FreshChoice (2/4·2/5 아침) · 트와이즐 Four Square (2/7 오후, 글렌태너·마운트쿡엔 마트 없음)', items: [
        { name: '빵 (보충)', qty: '1~2봉' }, { name: '우유 (보충)', qty: '2L × 1~2' }, { name: '계란 (보충)', qty: '12개' }, { name: '과일·채소 (보충)', qty: '2~3일치' },
        { name: '고기 (보충)', qty: '2끼분', note: '트와이즐에서, 글렌태너 2박용' },
        { name: '연어', qty: '한 끼분', note: '2/7 푸카키 연어 농장에서' },
        { name: '밀포드 가는 날 간식·물 확인', qty: '2/4 저녁' },
        { name: '생수 (보충)', qty: '2L × 2', note: '선택, 트와이즐' },
      ] },
    ],
    sources: [
      { title: "PAK'nSAVE Queenstown 매장 정보", url: 'https://www.paknsave.co.nz/south-island/otago-and-southland/queenstown' },
      { title: "Kim's Mart", url: 'https://www.kims.co.nz/' },
      { title: 'New Star Asian Market (The Landing)', url: 'https://www.thelandingqueenstown.co.nz/new-star/' },
      { title: 'Indie Campers 주방 키트 구성', url: 'https://help.indiecampers.com/hc/en-us/articles/360019400738-What-is-included-in-the-kitchen-kit' },
      { title: 'Wilderness 캠핑카 준비물 체크리스트', url: 'https://www.wilderness.co.nz/plan-your-trip/blog/campervan-packing-checklist' },
      { title: '뉴질랜드 환경부 · 일회용 플라스틱 금지', url: 'https://environment.govt.nz/what-you-can-do/campaigns/single-use-plastic-bags-banned/' },
      { title: '샌드플라이 대비 (Tourist Class NZ)', url: 'https://touristclassnz.com/the-milford-menace/' },
      { title: '마운트쿡 빌리지 상점 안내 (Hermitage)', url: 'https://www.hermitage.co.nz/experience/hermitage-retail-centre' },
    ],
  },

  credits: CREDITS,
};
